### ISSUE TITLE
Thinking of picking up Pascal for a fairly simple web game

### ISSUE THREAD

**Issue by Zireael07** [lainz/AllegroPas2JS-Demo-Game#1]
1) Now that we have a webassembly compiler in FreePascal, is there any reason to use pas2js over that? (Maybe ease of use?)
2) Does pas2js have any limitations I should be wary of when writing Pascal code?

**Comment by lainz** [comment]
1) Hi, I had no idea that we have webassembly. Not tested it so I can't say.

2) I'm not sure if limitations, I mean you at last resource can embeed javascript code directly.

But I recommend you to don't follow what I did in this demo. I noticed finally that Allegro.js is not fast, it uses normal canvas and images, not webgl. So the game must be really very simple to run it fast with Allegro.js. Better try using another library that's using webgl instead.

**Comment by Zireael07** [comment]
Apparently we do, although I'm not 100% sure how to use it: https://wiki.freepascal.org/WebAssembly/Compiler

Re: 2, I meant if I should avoid some constructs in Pascal code, like I heard somewhere that pas2js doesn't work with pointers?

**Comment by lainz** [comment]
Yes that's true. There are no pointers. I never use pointers when programming, I don't do low level stuff anyways.

The thing closer to a pointer to data is an array in JavaScript that is always passed as reference, as well objects. They are not copied when assigned, it works like a pointer.

https://stackoverflow.com/questions/10231868/pointers-in-javascript/10231963#:~:text=In%20JavaScript%2C%20like%20in%20C,variable%20in%20the%20original%20object.

**Comment by lainz** [comment]
I was checking your profile and seems that you know more of game programming than me. Why using Pascal at all?

**Comment by lainz** [comment]
If you want to pick a new language for learning I can recommend you Kotlin. You will have a code that works for web and android. Edit: checked and now it goes native as well, so one of the languages supported everywhere

**Comment by lainz** [comment]
Well since it isn't an issue I close it. Maybe you can get a better answer in the Lazarus forums.
